version: '3.5' 
services: 
  consul: 
    image: consul:latest
    container_name: consul
    networks:
      - dockr    
    ports: 
      - '8300:8300' 
      - '8301:8301' 
      - '8301:8301/udp' 
      - '8500:8500' 
      - '8600:8600' 
      - '8600:8600/udp'

  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin    
    networks:
      - dockr
    ports:
      - '9411:9411'
      
  api-gateway:
    image: tripzalk/tripza-api-gateway:latest
    container_name: api-gateway      
    ports:
      - '8089:8089'
    environment:  
      - SPR_PROFILE=local
      - CONSUL_URL=192.168.1.149
      - LOGSTASH_URL=192.168.1.149
    networks:
      - dockr
    depends_on: 
      - consul    
      
  config-server:
    image: tripzalk/tripza-config-server:latest
    container_name: config-server      
    networks:
      - dockr    
    depends_on: 
      - consul
    environment:  
      - SPR_PROFILE=local
      - CONSUL_URL=192.168.1.149
      - LOGSTASH_URL=192.168.1.149

  elasticsearch:
    image: elasticsearch:$ELK_VERSION
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    container_name: elasticsearch        
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      discovery.type: single-node
    ports:
      - '9200:9200'
      - '9300:9300'
    networks:
      - dockr
    restart: unless-stopped

  logstash:
    image: logstash:$ELK_VERSION
    container_name: logstash     
    ports:
      - '5000:5000'
      - '9600:9600'
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
      XPACK_MONITORING_ELASTICSEARCH_HOSTS: "elasticsearch:9200"
      XPACK_MONITORING_ENABLED: "true"
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    networks:
      - dockr
    restart: unless-stopped
    depends_on:
      - elasticsearch

  kibana:
    image: kibana:${ELK_VERSION}
    container_name: kibana    
    environment:
      XPACK_MONITORING_UI_CONTAINER_ELASTICSEARCH_ENABLED: "true"
    ports:
      - '5601:5601'
    networks:
      - dockr
    restart: unless-stopped
    depends_on:
      - elasticsearch
      - logstash

networks:
  dockr:
volumes:
  elasticsearch: